application: sonorous-cacao-89706
version: prod
runtime: php55
api_version: 1
threadsafe: true

handlers:
###################################################

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

#- url: /favicon.ico
#  static_files: public/favicon.ico
#  upload: public/favicon.ico

- url: /css
  static_dir: public/css

- url: /img
  static_dir: public/img

- url: /strip
  static_dir: public/strip

- url: /js
  static_dir: public/js

####################################################

- url: /sitemap.xml
  script: src/sitemap.php

- url: /404/?
  script: src/xkcd404.php

- url: /[0-9]+/?
  script: src/strip.php

- url: /
  script: src/index.php

- url: /recommand
  script: src/recommand.php

- url: /api/strip/original/[0-9]+
  script: src/api_strip_original.php

- url: /api/recommand/[0-9]+
  script: src/api_recommand.php

- url: /api/list_recommand/?
  script: src/api_list_recommand.php

- url: /.*
  script: src/error404.php

###################################################

#error_handlers:
#- file: error/default.html

# - error_code: over_quota
#   file: error/over_quota.html

# - error_code: dos_api_denial
#   file: error/over_quota.html
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- asset/
- .git/
