runtime: php72

handlers:
###################################################

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
  secure: always

#- url: /favicon.ico
#  static_files: public/favicon.ico
#  upload: public/favicon.ico

- url: /css
  static_dir: public/css
  secure: always

- url: /img
  static_dir: public/img
  secure: always

- url: /strip
  static_dir: public/strip
  secure: always

- url: /js
  static_dir: public/js
  secure: always

- url: /s
  static_dir: public/s
  secure: always

###################################################

#error_handlers:
#- file: error/default.html

# - error_code: over_quota
#   file: error/over_quota.html

# - error_code: dos_api_denial
#   file: error/over_quota.html
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- asset/
- doc/
- bin/
- .git/
